# Generated by Django 4.2.6 on 2024-05-01 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='phone_no',
            new_name='contact_no',
        ),
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages_known', models.CharField(default='languages known', max_length=800)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='project_name', max_length=800)),
                ('tools_used', models.CharField(default='company name', max_length=800)),
                ('project_link', models.CharField(default='project link', max_length=800)),
                ('description', models.CharField(default='project description', max_length=1000)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='first name', max_length=800)),
                ('last_name', models.CharField(default='last name', max_length=800)),
                ('contact_no', models.CharField(default='contact number', max_length=800)),
                ('email', models.CharField(default='email', max_length=800)),
                ('linkedin_url', models.CharField(default='linkedin url', max_length=800)),
                ('summary', models.CharField(default='profile summary', max_length=800)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(default='designation', max_length=800)),
                ('company_name', models.CharField(default='company name', max_length=800)),
                ('from_date', models.CharField(default='from date', max_length=800)),
                ('to_date', models.CharField(default='to date', max_length=800)),
                ('description', models.CharField(default='experience description', max_length=1000)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(default='college name', max_length=800)),
                ('education', models.CharField(default='education', max_length=800)),
                ('from_date', models.CharField(default='from date', max_length=800)),
                ('to_date', models.CharField(default='to date', max_length=800)),
                ('city', models.CharField(default='city', max_length=800)),
                ('cgpa', models.CharField(default='CGPA', max_length=800)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificates', models.CharField(default='certificates', max_length=800)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acheivements', models.CharField(default='achievements', max_length=800)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
