# Generated by Django 4.1.7 on 2024-05-03 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0003_user_skills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='skills',
            new_name='languages',
        ),
    ]
