# Generated by Django 4.1.7 on 2024-05-03 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0004_rename_skills_languages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='education',
            new_name='degree',
        ),
    ]
