# Generated by Django 4.2.6 on 2024-05-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0005_rename_education_education_degree'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplatesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_image', models.ImageField(default='profile', upload_to='uploaded_images/')),
                ('view_name', models.CharField(default='none', max_length=300)),
            ],
        ),
    ]
