# Generated by Django 4.2.6 on 2024-05-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0006_templatesinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatesinfo',
            name='id_name',
            field=models.CharField(default='none', max_length=300),
        ),
    ]
