# Generated by Django 4.1.7 on 2024-05-04 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0007_resume_extracted_resumedetails_and_more'),
        ('resume_builder', '0007_templatesinfo_id_name'),
    ]

    operations = [
    ]
