# Generated by Django 4.1.7 on 2024-05-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0008_merge_20240504_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracted_educationdetails',
            name='id_name',
            field=models.CharField(default='none', max_length=300),
        ),
    ]
