# Generated by Django 4.2.6 on 2024-05-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0009_extracted_educationdetails_id_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatesinfo',
            name='price',
            field=models.CharField(default='30', max_length=100),
        ),
    ]
